### ISSUE TITLE
Broken links under ReadMe 'Learn More'

### ISSUE THREAD

**Issue by soniariv** [OfficeDev/Excel-Add-in-JS-ExternalDataGitHub#4]
Under the Microsoft OfficeDev doc at https://github.com/OfficeDev/Excel-Add-in-JS-ExternalDataGitHub/blob/master/Readme.md

last paragraph 'Learn More' displays 5 references for further documentations:

1.Excel Add-ins programming overview
2.Snippet Explorer for Excel
3.Excel Add-ins code samples
4.Excel Add-ins JavaScript API Reference
5.Build your first Excel Add-in

Unfortunately they are all broken links or a 404 error appears.
Hope this Issue #  helps someone at Microsoft OfficeDev in order to fix the issue. 
Thank you.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
